var car = 'subaru';
console.log('is car =="subaru"? i predict true');
console.log(car == 'subaru');
console.log("is car ===\"subaru\"? i predict true");
console.log(car === "subaru");
console.log("is car != \"toyota\"? i predict true");
console.log(car != "toyota");
console.log("is car !==\"toyota\"? i predict true ");
console.log(car !== "toyota");
console.log("is car ==\"subaru\"? i predict true");
console.log(car == "subaru");
// false stAtment
console.log("is car ==undefined? i predict false");
console.log(car == undefined);
console.log("is car ===\"toyota\"? i predict false");
console.log(car === "toyota");
console.log("is car ===null? i predict true");
console.log(car === null);
console.log("is car != \"subaru\"? i predict false");
console.log(car != "subaru");
console.log("is car !== \"subaru\"? i oredict false");
console.log(car !== "subaru");
